<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timePb.proto

namespace GPBMetadata;

class TimePb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a0c74696d6550622e70726f746f2281010a0654696d655062120c0a0464617465180120012809120d0a056d6f6e7468180220012809120c0a047965617218032001280912140a0c6d696c6c697365636f6e647318042001280312150a0d666f726d617474656444617465180520012809121f0a0874696d657a6f6e6518062001280e320d2e54696d655a6f6e65456e756d2a370a0c54696d655a6f6e65456e756d12150a11554e4b4e4f574e5f54494d455f5a4f4e45100012070a03495354100112070a035554431002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

