<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timePb.proto

/**
 * Protobuf type <code>TimeZoneEnum</code>
 */
class TimeZoneEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_TIME_ZONE = 0;</code>
     */
    const UNKNOWN_TIME_ZONE = 0;
    /**
     * Generated from protobuf enum <code>IST = 1;</code>
     */
    const IST = 1;
    /**
     * Generated from protobuf enum <code>UTC = 2;</code>
     */
    const UTC = 2;

    private static $valueToName = [
        self::UNKNOWN_TIME_ZONE => 'UNKNOWN_TIME_ZONE',
        self::IST => 'IST',
        self::UTC => 'UTC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

