<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AddressPb</code>
 */
class AddressPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string homeNo = 1;</code>
     */
    protected $homeNo = '';
    /**
     * Generated from protobuf field <code>string street = 2;</code>
     */
    protected $street = '';
    /**
     * Generated from protobuf field <code>string landMark = 3;</code>
     */
    protected $landMark = '';
    /**
     * Generated from protobuf field <code>.CityEnum city = 4;</code>
     */
    protected $city = 0;
    /**
     * Generated from protobuf field <code>.StateEnum state = 5;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>int32 pincode = 6;</code>
     */
    protected $pincode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $homeNo
     *     @type string $street
     *     @type string $landMark
     *     @type int $city
     *     @type int $state
     *     @type int $pincode
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\AddressPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string homeNo = 1;</code>
     * @return string
     */
    public function getHomeNo()
    {
        return $this->homeNo;
    }

    /**
     * Generated from protobuf field <code>string homeNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHomeNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->homeNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street = 2;</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Generated from protobuf field <code>string street = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string landMark = 3;</code>
     * @return string
     */
    public function getLandMark()
    {
        return $this->landMark;
    }

    /**
     * Generated from protobuf field <code>string landMark = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLandMark($var)
    {
        GPBUtil::checkString($var, True);
        $this->landMark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CityEnum city = 4;</code>
     * @return int
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>.CityEnum city = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\CityEnum::class);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.StateEnum state = 5;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.StateEnum state = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\StateEnum::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pincode = 6;</code>
     * @return int
     */
    public function getPincode()
    {
        return $this->pincode;
    }

    /**
     * Generated from protobuf field <code>int32 pincode = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPincode($var)
    {
        GPBUtil::checkInt32($var);
        $this->pincode = $var;

        return $this;
    }

}

