<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>AvailabilityStatusEnum</code>
 */
class AvailabilityStatusEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_AVAILABILITY_STATUS = 0;</code>
     */
    const UNKNOWN_AVAILABILITY_STATUS = 0;
    /**
     * Generated from protobuf enum <code>AVAILABLE = 1;</code>
     */
    const AVAILABLE = 1;
    /**
     * Generated from protobuf enum <code>NOT_AVAILABLE = 2;</code>
     */
    const NOT_AVAILABLE = 2;

    private static $valueToName = [
        self::UNKNOWN_AVAILABILITY_STATUS => 'UNKNOWN_AVAILABILITY_STATUS',
        self::AVAILABLE => 'AVAILABLE',
        self::NOT_AVAILABLE => 'NOT_AVAILABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

