<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booleanPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>BooleanEnum</code>
 */
class BooleanEnum
{
    /**
     * Generated from protobuf enum <code>DEFAULT = 0;</code>
     */
    const PBDEFAULT = 0;
    /**
     * Generated from protobuf enum <code>TRUE = 1;</code>
     */
    const TRUE = 1;
    /**
     * Generated from protobuf enum <code>FALSE = 2;</code>
     */
    const FALSE = 2;

    private static $valueToName = [
        self::PBDEFAULT => 'PBDEFAULT',
        self::TRUE => 'TRUE',
        self::FALSE => 'FALSE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

