<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BuyPb</code>
 */
class BuyPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     */
    protected $orderId = '';
    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     */
    protected $customerRef = null;
    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     */
    protected $itemRef = null;
    /**
     * Generated from protobuf field <code>.DeliveryManRefPb deliveryManRef = 5;</code>
     */
    protected $deliveryManRef = null;
    /**
     * Generated from protobuf field <code>int32 quantity = 6;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>float price = 7;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 8;</code>
     */
    protected $deliveryStatus = 0;
    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     */
    protected $time = null;
    /**
     * Generated from protobuf field <code>.PaymentPbRef paymentRef = 10;</code>
     */
    protected $paymentRef = null;
    /**
     * Generated from protobuf field <code>string parentOrderId = 11;</code>
     */
    protected $parentOrderId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type string $orderId
     *     @type \App\Protobuff\CustomerPbRef $customerRef
     *     @type \App\Protobuff\ItemPbRef $itemRef
     *     @type \App\Protobuff\DeliveryManRefPb $deliveryManRef
     *     @type int $quantity
     *     @type float $price
     *     @type int $deliveryStatus
     *     @type \App\Protobuff\TimePb $time
     *     @type \App\Protobuff\PaymentPbRef $paymentRef
     *     @type string $parentOrderId
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\BuyPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return $this->dbInfo;
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     * @return \App\Protobuff\CustomerPbRef
     */
    public function getCustomerRef()
    {
        return $this->customerRef;
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     * @param \App\Protobuff\CustomerPbRef $var
     * @return $this
     */
    public function setCustomerRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\CustomerPbRef::class);
        $this->customerRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     * @return \App\Protobuff\ItemPbRef
     */
    public function getItemRef()
    {
        return $this->itemRef;
    }

    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     * @param \App\Protobuff\ItemPbRef $var
     * @return $this
     */
    public function setItemRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ItemPbRef::class);
        $this->itemRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DeliveryManRefPb deliveryManRef = 5;</code>
     * @return \App\Protobuff\DeliveryManRefPb
     */
    public function getDeliveryManRef()
    {
        return $this->deliveryManRef;
    }

    /**
     * Generated from protobuf field <code>.DeliveryManRefPb deliveryManRef = 5;</code>
     * @param \App\Protobuff\DeliveryManRefPb $var
     * @return $this
     */
    public function setDeliveryManRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\DeliveryManRefPb::class);
        $this->deliveryManRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 6;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 7;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 8;</code>
     * @return int
     */
    public function getDeliveryStatus()
    {
        return $this->deliveryStatus;
    }

    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliveryStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\DeliveryStatusEnum::class);
        $this->deliveryStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PaymentPbRef paymentRef = 10;</code>
     * @return \App\Protobuff\PaymentPbRef
     */
    public function getPaymentRef()
    {
        return $this->paymentRef;
    }

    /**
     * Generated from protobuf field <code>.PaymentPbRef paymentRef = 10;</code>
     * @param \App\Protobuff\PaymentPbRef $var
     * @return $this
     */
    public function setPaymentRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\PaymentPbRef::class);
        $this->paymentRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 11;</code>
     * @return string
     */
    public function getParentOrderId()
    {
        return $this->parentOrderId;
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setParentOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parentOrderId = $var;

        return $this;
    }

}

