<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BuyPb</code>
 */
class BuyPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     */
    protected $orderId = '';
    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     */
    protected $customerRef = null;
    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     */
    protected $itemRef = null;
    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>float price = 6;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 7;</code>
     */
    protected $deliveryStatus = 0;
    /**
     * Generated from protobuf field <code>.TimePb time = 8;</code>
     */
    protected $time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type string $orderId
     *     @type \App\Protobuff\CustomerPbRef $customerRef
     *     @type \App\Protobuff\ItemPbRef $itemRef
     *     @type int $quantity
     *     @type float $price
     *     @type int $deliveryStatus
     *     @type \App\Protobuff\TimePb $time
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\BuyPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return isset($this->dbInfo) ? $this->dbInfo : null;
    }

    public function hasDbInfo()
    {
        return isset($this->dbInfo);
    }

    public function clearDbInfo()
    {
        unset($this->dbInfo);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>string orderId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     * @return \App\Protobuff\CustomerPbRef
     */
    public function getCustomerRef()
    {
        return isset($this->customerRef) ? $this->customerRef : null;
    }

    public function hasCustomerRef()
    {
        return isset($this->customerRef);
    }

    public function clearCustomerRef()
    {
        unset($this->customerRef);
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 3;</code>
     * @param \App\Protobuff\CustomerPbRef $var
     * @return $this
     */
    public function setCustomerRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\CustomerPbRef::class);
        $this->customerRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     * @return \App\Protobuff\ItemPbRef
     */
    public function getItemRef()
    {
        return isset($this->itemRef) ? $this->itemRef : null;
    }

    public function hasItemRef()
    {
        return isset($this->itemRef);
    }

    public function clearItemRef()
    {
        unset($this->itemRef);
    }

    /**
     * Generated from protobuf field <code>.ItemPbRef itemRef = 4;</code>
     * @param \App\Protobuff\ItemPbRef $var
     * @return $this
     */
    public function setItemRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ItemPbRef::class);
        $this->itemRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 6;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 7;</code>
     * @return int
     */
    public function getDeliveryStatus()
    {
        return $this->deliveryStatus;
    }

    /**
     * Generated from protobuf field <code>.DeliveryStatusEnum deliveryStatus = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDeliveryStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\DeliveryStatusEnum::class);
        $this->deliveryStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 8;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : null;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 8;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

}

