<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BuySearchRequestPb</code>
 */
class BuySearchRequestPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string parentOrderId = 1;</code>
     */
    protected $parentOrderId = '';
    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     */
    protected $customerId = '';
    /**
     * Generated from protobuf field <code>string deliveryManRefId = 3;</code>
     */
    protected $deliveryManRefId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parentOrderId
     *     @type string $customerId
     *     @type string $deliveryManRefId
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\BuyPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 1;</code>
     * @return string
     */
    public function getParentOrderId()
    {
        return $this->parentOrderId;
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParentOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parentOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deliveryManRefId = 3;</code>
     * @return string
     */
    public function getDeliveryManRefId()
    {
        return $this->deliveryManRefId;
    }

    /**
     * Generated from protobuf field <code>string deliveryManRefId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeliveryManRefId($var)
    {
        GPBUtil::checkString($var, True);
        $this->deliveryManRefId = $var;

        return $this;
    }

}

