<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>CityEnum</code>
 */
class CityEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_CITY = 0;</code>
     */
    const UNKNOWN_CITY = 0;
    /**
     * Generated from protobuf enum <code>LUCKNOW = 1;</code>
     */
    const LUCKNOW = 1;
    /**
     * Generated from protobuf enum <code>SITAPUR = 2;</code>
     */
    const SITAPUR = 2;

    private static $valueToName = [
        self::UNKNOWN_CITY => 'UNKNOWN_CITY',
        self::LUCKNOW => 'LUCKNOW',
        self::SITAPUR => 'SITAPUR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

