<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confirmOrderDeliveryPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ConfirmOrderDeliveryPb</code>
 */
class ConfirmOrderDeliveryPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     */
    protected $customerId = '';
    /**
     * Generated from protobuf field <code>string parentOrderId = 2;</code>
     */
    protected $parentOrderId = '';
    /**
     * Generated from protobuf field <code>repeated .BuyPb orderList = 3;</code>
     */
    private $orderList;
    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     */
    protected $time = null;
    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum status = 5;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>repeated string data = 6;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customerId
     *     @type string $parentOrderId
     *     @type \App\Protobuff\BuyPb[]|\Google\Protobuf\Internal\RepeatedField $orderList
     *     @type \App\Protobuff\TimePb $time
     *     @type int $status
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $data
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ConfirmOrderDeliveryPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 2;</code>
     * @return string
     */
    public function getParentOrderId()
    {
        return $this->parentOrderId;
    }

    /**
     * Generated from protobuf field <code>string parentOrderId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parentOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BuyPb orderList = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderList()
    {
        return $this->orderList;
    }

    /**
     * Generated from protobuf field <code>repeated .BuyPb orderList = 3;</code>
     * @param \App\Protobuff\BuyPb[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protobuff\BuyPb::class);
        $this->orderList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : null;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\IsOrderedPlacedEnum::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string data = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated string data = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

}

