<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactDetailPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ContactDetailPb</code>
 */
class ContactDetailPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EmailPb email = 1;</code>
     */
    protected $email = null;
    /**
     * Generated from protobuf field <code>.MobilePb mobile = 2;</code>
     */
    protected $mobile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EmailPb $email
     *     @type \App\Protobuff\MobilePb $mobile
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ContactDetailPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EmailPb email = 1;</code>
     * @return \App\Protobuff\EmailPb
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>.EmailPb email = 1;</code>
     * @param \App\Protobuff\EmailPb $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EmailPb::class);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MobilePb mobile = 2;</code>
     * @return \App\Protobuff\MobilePb
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>.MobilePb mobile = 2;</code>
     * @param \App\Protobuff\MobilePb $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\MobilePb::class);
        $this->mobile = $var;

        return $this;
    }

}

