<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CreateBuyRequestPb</code>
 */
class CreateBuyRequestPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     */
    protected $customerId = '';
    /**
     * Generated from protobuf field <code>repeated string itemIdAndQuantity = 2;</code>
     */
    private $itemIdAndQuantity;
    /**
     * Generated from protobuf field <code>string paymentRefId = 3;</code>
     */
    protected $paymentRefId = '';
    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum isOrderPlaced = 4;</code>
     */
    protected $isOrderPlaced = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customerId
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $itemIdAndQuantity
     *     @type string $paymentRefId
     *     @type int $isOrderPlaced
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\BuyPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string itemIdAndQuantity = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemIdAndQuantity()
    {
        return $this->itemIdAndQuantity;
    }

    /**
     * Generated from protobuf field <code>repeated string itemIdAndQuantity = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemIdAndQuantity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->itemIdAndQuantity = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paymentRefId = 3;</code>
     * @return string
     */
    public function getPaymentRefId()
    {
        return $this->paymentRefId;
    }

    /**
     * Generated from protobuf field <code>string paymentRefId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentRefId($var)
    {
        GPBUtil::checkString($var, True);
        $this->paymentRefId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum isOrderPlaced = 4;</code>
     * @return int
     */
    public function getIsOrderPlaced()
    {
        return $this->isOrderPlaced;
    }

    /**
     * Generated from protobuf field <code>.IsOrderedPlacedEnum isOrderPlaced = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setIsOrderPlaced($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\IsOrderedPlacedEnum::class);
        $this->isOrderPlaced = $var;

        return $this;
    }

}

