<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customerPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CustomerSearchRequestPb</code>
 */
class CustomerSearchRequestPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PrivilegeTypeEnum privilege = 1;</code>
     */
    protected $privilege = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $privilege
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\CustomerPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.PrivilegeTypeEnum privilege = 1;</code>
     * @return int
     */
    public function getPrivilege()
    {
        return $this->privilege;
    }

    /**
     * Generated from protobuf field <code>.PrivilegeTypeEnum privilege = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrivilege($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\PrivilegeTypeEnum::class);
        $this->privilege = $var;

        return $this;
    }

}

