<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customerPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CustomerPbRef</code>
 */
class CustomerPbRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     */
    protected $contact = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \App\Protobuff\NamePb $name
     *     @type \App\Protobuff\ContactDetailPb $contact
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\CustomerPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     * @return \App\Protobuff\NamePb
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     * @param \App\Protobuff\NamePb $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\NamePb::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     * @return \App\Protobuff\ContactDetailPb
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     * @param \App\Protobuff\ContactDetailPb $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ContactDetailPb::class);
        $this->contact = $var;

        return $this;
    }

}

