<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deliveryManPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DeliveryManPb</code>
 */
class DeliveryManPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     */
    protected $contact = null;
    /**
     * Generated from protobuf field <code>.ImageRefPb profileImage = 4;</code>
     */
    protected $profileImage = null;
    /**
     * Generated from protobuf field <code>string adharNo = 5;</code>
     */
    protected $adharNo = '';
    /**
     * Generated from protobuf field <code>.TimePb time = 6;</code>
     */
    protected $time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type \App\Protobuff\NamePb $name
     *     @type \App\Protobuff\ContactDetailPb $contact
     *     @type \App\Protobuff\ImageRefPb $profileImage
     *     @type string $adharNo
     *     @type \App\Protobuff\TimePb $time
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\DeliveryManPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return isset($this->dbInfo) ? $this->dbInfo : null;
    }

    public function hasDbInfo()
    {
        return isset($this->dbInfo);
    }

    public function clearDbInfo()
    {
        unset($this->dbInfo);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     * @return \App\Protobuff\NamePb
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : null;
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>.NamePb name = 2;</code>
     * @param \App\Protobuff\NamePb $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\NamePb::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     * @return \App\Protobuff\ContactDetailPb
     */
    public function getContact()
    {
        return isset($this->contact) ? $this->contact : null;
    }

    public function hasContact()
    {
        return isset($this->contact);
    }

    public function clearContact()
    {
        unset($this->contact);
    }

    /**
     * Generated from protobuf field <code>.ContactDetailPb contact = 3;</code>
     * @param \App\Protobuff\ContactDetailPb $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ContactDetailPb::class);
        $this->contact = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ImageRefPb profileImage = 4;</code>
     * @return \App\Protobuff\ImageRefPb
     */
    public function getProfileImage()
    {
        return isset($this->profileImage) ? $this->profileImage : null;
    }

    public function hasProfileImage()
    {
        return isset($this->profileImage);
    }

    public function clearProfileImage()
    {
        unset($this->profileImage);
    }

    /**
     * Generated from protobuf field <code>.ImageRefPb profileImage = 4;</code>
     * @param \App\Protobuff\ImageRefPb $var
     * @return $this
     */
    public function setProfileImage($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ImageRefPb::class);
        $this->profileImage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string adharNo = 5;</code>
     * @return string
     */
    public function getAdharNo()
    {
        return $this->adharNo;
    }

    /**
     * Generated from protobuf field <code>string adharNo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAdharNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->adharNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 6;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : null;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 6;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

}

