<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactDetailPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EmailPb</code>
 */
class EmailPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string localPart = 1;</code>
     */
    protected $localPart = '';
    /**
     * Generated from protobuf field <code>string domainPart = 2;</code>
     */
    protected $domainPart = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $localPart
     *     @type string $domainPart
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ContactDetailPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string localPart = 1;</code>
     * @return string
     */
    public function getLocalPart()
    {
        return $this->localPart;
    }

    /**
     * Generated from protobuf field <code>string localPart = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalPart($var)
    {
        GPBUtil::checkString($var, True);
        $this->localPart = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domainPart = 2;</code>
     * @return string
     */
    public function getDomainPart()
    {
        return $this->domainPart;
    }

    /**
     * Generated from protobuf field <code>string domainPart = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainPart($var)
    {
        GPBUtil::checkString($var, True);
        $this->domainPart = $var;

        return $this;
    }

}

