<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactDetailPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EmailBuilderPb</code>
 */
class EmailBuilderPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string to = 1;</code>
     */
    protected $to = '';
    /**
     * Generated from protobuf field <code>string reciverName = 2;</code>
     */
    protected $reciverName = '';
    /**
     * Generated from protobuf field <code>string subject = 3;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string body = 4;</code>
     */
    protected $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $to
     *     @type string $reciverName
     *     @type string $subject
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ContactDetailPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string to = 1;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>string to = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reciverName = 2;</code>
     * @return string
     */
    public function getReciverName()
    {
        return $this->reciverName;
    }

    /**
     * Generated from protobuf field <code>string reciverName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReciverName($var)
    {
        GPBUtil::checkString($var, True);
        $this->reciverName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 3;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

}

