<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EntityPb</code>
 */
class EntityPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.LifetimeEnum lifetime = 2;</code>
     */
    protected $lifetime = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $lifetime
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Entity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LifetimeEnum lifetime = 2;</code>
     * @return int
     */
    public function getLifetime()
    {
        return $this->lifetime;
    }

    /**
     * Generated from protobuf field <code>.LifetimeEnum lifetime = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLifetime($var)
    {
        GPBUtil::checkEnum($var, \LifetimeEnum::class);
        $this->lifetime = $var;

        return $this;
    }

}

