<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagePb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>ImageTypeEnum</code>
 */
class ImageTypeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_IMAGE_TYPE = 0;</code>
     */
    const UNKNOWN_IMAGE_TYPE = 0;
    /**
     * Generated from protobuf enum <code>PROFILE_IMAGE = 1;</code>
     */
    const PROFILE_IMAGE = 1;
    /**
     * Generated from protobuf enum <code>ITEM_IMAGE = 2;</code>
     */
    const ITEM_IMAGE = 2;
    /**
     * Generated from protobuf enum <code>BANNER_IMAGE = 3;</code>
     */
    const BANNER_IMAGE = 3;
    /**
     * Generated from protobuf enum <code>BADGE_IMAGE = 4;</code>
     */
    const BADGE_IMAGE = 4;

    private static $valueToName = [
        self::UNKNOWN_IMAGE_TYPE => 'UNKNOWN_IMAGE_TYPE',
        self::PROFILE_IMAGE => 'PROFILE_IMAGE',
        self::ITEM_IMAGE => 'ITEM_IMAGE',
        self::BANNER_IMAGE => 'BANNER_IMAGE',
        self::BADGE_IMAGE => 'BADGE_IMAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

