<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagePb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ImageSearchRequestPb</code>
 */
class ImageSearchRequestPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string imageId = 1;</code>
     */
    protected $imageId = '';
    /**
     * Generated from protobuf field <code>.ImageTypeEnum imageType = 2;</code>
     */
    protected $imageType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $imageId
     *     @type int $imageType
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ImagePb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string imageId = 1;</code>
     * @return string
     */
    public function getImageId()
    {
        return $this->imageId;
    }

    /**
     * Generated from protobuf field <code>string imageId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ImageTypeEnum imageType = 2;</code>
     * @return int
     */
    public function getImageType()
    {
        return $this->imageType;
    }

    /**
     * Generated from protobuf field <code>.ImageTypeEnum imageType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setImageType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\ImageTypeEnum::class);
        $this->imageType = $var;

        return $this;
    }

}

