<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>IsOrderedPlacedEnum</code>
 */
class IsOrderedPlacedEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ORDER = 0;</code>
     */
    const UNKNOWN_ORDER = 0;
    /**
     * Generated from protobuf enum <code>ORDER_FAILED = 1;</code>
     */
    const ORDER_FAILED = 1;
    /**
     * Generated from protobuf enum <code>ORDER_SUCCESS = 2;</code>
     */
    const ORDER_SUCCESS = 2;

    private static $valueToName = [
        self::UNKNOWN_ORDER => 'UNKNOWN_ORDER',
        self::ORDER_FAILED => 'ORDER_FAILED',
        self::ORDER_SUCCESS => 'ORDER_SUCCESS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

