<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>ItemTypeEnum</code>
 */
class ItemTypeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ITEM_TYPE = 0;</code>
     */
    const UNKNOWN_ITEM_TYPE = 0;
    /**
     * Generated from protobuf enum <code>VEGETABLES = 1;</code>
     */
    const VEGETABLES = 1;
    /**
     * Generated from protobuf enum <code>FRUITS = 2;</code>
     */
    const FRUITS = 2;
    /**
     * Generated from protobuf enum <code>MILK = 3;</code>
     */
    const MILK = 3;
    /**
     * Generated from protobuf enum <code>BEVERAGES = 4;</code>
     */
    const BEVERAGES = 4;

    private static $valueToName = [
        self::UNKNOWN_ITEM_TYPE => 'UNKNOWN_ITEM_TYPE',
        self::VEGETABLES => 'VEGETABLES',
        self::FRUITS => 'FRUITS',
        self::MILK => 'MILK',
        self::BEVERAGES => 'BEVERAGES',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

