<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ItemPbRef</code>
 */
class ItemPbRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     */
    protected $itemName = null;
    /**
     * Generated from protobuf field <code>float price = 3;</code>
     */
    protected $price = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \App\Protobuff\NamePb $itemName
     *     @type float $price
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ItemPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @return \App\Protobuff\NamePb
     */
    public function getItemName()
    {
        return isset($this->itemName) ? $this->itemName : null;
    }

    public function hasItemName()
    {
        return isset($this->itemName);
    }

    public function clearItemName()
    {
        unset($this->itemName);
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @param \App\Protobuff\NamePb $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\NamePb::class);
        $this->itemName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

}

