<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ItemPb</code>
 */
class ItemPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     */
    protected $itemName = null;
    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     */
    protected $itemUrl = null;
    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     */
    protected $quantity = '';
    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     */
    protected $itemType = 0;
    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     */
    protected $availabilityStatus = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type \App\Protobuff\NamePb $itemName
     *     @type \App\Protobuff\ImagePb $itemUrl
     *     @type string $quantity
     *     @type int $price
     *     @type int $itemType
     *     @type int $availabilityStatus
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ItemPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return isset($this->dbInfo) ? $this->dbInfo : null;
    }

    public function hasDbInfo()
    {
        return isset($this->dbInfo);
    }

    public function clearDbInfo()
    {
        unset($this->dbInfo);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @return \App\Protobuff\NamePb
     */
    public function getItemName()
    {
        return isset($this->itemName) ? $this->itemName : null;
    }

    public function hasItemName()
    {
        return isset($this->itemName);
    }

    public function clearItemName()
    {
        unset($this->itemName);
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @param \App\Protobuff\NamePb $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\NamePb::class);
        $this->itemName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     * @return \App\Protobuff\ImagePb
     */
    public function getItemUrl()
    {
        return isset($this->itemUrl) ? $this->itemUrl : null;
    }

    public function hasItemUrl()
    {
        return isset($this->itemUrl);
    }

    public function clearItemUrl()
    {
        unset($this->itemUrl);
    }

    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     * @param \App\Protobuff\ImagePb $var
     * @return $this
     */
    public function setItemUrl($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ImagePb::class);
        $this->itemUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     * @return string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int32 price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     * @return int
     */
    public function getItemType()
    {
        return $this->itemType;
    }

    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\ItemTypeEnum::class);
        $this->itemType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     * @return int
     */
    public function getAvailabilityStatus()
    {
        return $this->availabilityStatus;
    }

    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAvailabilityStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\AvailabilityStatusEnum::class);
        $this->availabilityStatus = $var;

        return $this;
    }

}

