<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itemPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ItemPb</code>
 */
class ItemPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     */
    protected $itemName = null;
    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     */
    protected $itemUrl = null;
    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     */
    protected $quantity = '';
    /**
     * Generated from protobuf field <code>float price = 5;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     */
    protected $itemType = 0;
    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     */
    protected $availabilityStatus = 0;
    /**
     * Generated from protobuf field <code>.ItemQuantityTypeEnum quantityType = 8;</code>
     */
    protected $quantityType = 0;
    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     */
    protected $time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type \App\Protobuff\NamePb $itemName
     *     @type \App\Protobuff\ImagePb $itemUrl
     *     @type string $quantity
     *     @type float $price
     *     @type int $itemType
     *     @type int $availabilityStatus
     *     @type int $quantityType
     *     @type \App\Protobuff\TimePb $time
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ItemPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return $this->dbInfo;
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @return \App\Protobuff\NamePb
     */
    public function getItemName()
    {
        return $this->itemName;
    }

    /**
     * Generated from protobuf field <code>.NamePb itemName = 2;</code>
     * @param \App\Protobuff\NamePb $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\NamePb::class);
        $this->itemName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     * @return \App\Protobuff\ImagePb
     */
    public function getItemUrl()
    {
        return $this->itemUrl;
    }

    /**
     * Generated from protobuf field <code>.ImagePb itemUrl = 3;</code>
     * @param \App\Protobuff\ImagePb $var
     * @return $this
     */
    public function setItemUrl($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\ImagePb::class);
        $this->itemUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     * @return string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>string quantity = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 5;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     * @return int
     */
    public function getItemType()
    {
        return $this->itemType;
    }

    /**
     * Generated from protobuf field <code>.ItemTypeEnum itemType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\ItemTypeEnum::class);
        $this->itemType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     * @return int
     */
    public function getAvailabilityStatus()
    {
        return $this->availabilityStatus;
    }

    /**
     * Generated from protobuf field <code>.AvailabilityStatusEnum availabilityStatus = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAvailabilityStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\AvailabilityStatusEnum::class);
        $this->availabilityStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ItemQuantityTypeEnum quantityType = 8;</code>
     * @return int
     */
    public function getQuantityType()
    {
        return $this->quantityType;
    }

    /**
     * Generated from protobuf field <code>.ItemQuantityTypeEnum quantityType = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantityType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\ItemQuantityTypeEnum::class);
        $this->quantityType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 9;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

}

