<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

/**
 * Protobuf type <code>LifetimeEnum</code>
 */
class LifetimeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>ACTIVE = 1;</code>
     */
    const ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>DELETE = 2;</code>
     */
    const DELETE = 2;
    /**
     * Generated from protobuf enum <code>BLOCK = 3;</code>
     */
    const BLOCK = 3;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::ACTIVE => 'ACTIVE',
        self::DELETE => 'DELETE',
        self::BLOCK => 'BLOCK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

