<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactDetailPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MobilePb</code>
 */
class MobilePb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mobileNo = 1;</code>
     */
    protected $mobileNo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mobileNo
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\ContactDetailPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mobileNo = 1;</code>
     * @return string
     */
    public function getMobileNo()
    {
        return $this->mobileNo;
    }

    /**
     * Generated from protobuf field <code>string mobileNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobileNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobileNo = $var;

        return $this;
    }

}

