<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namePb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NamePb</code>
 */
class NamePb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     */
    protected $firstName = '';
    /**
     * Generated from protobuf field <code>string lastName = 2;</code>
     */
    protected $lastName = '';
    /**
     * Generated from protobuf field <code>string canonicalName = 3;</code>
     */
    protected $canonicalName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $firstName
     *     @type string $lastName
     *     @type string $canonicalName
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\NamePb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastName = 2;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Generated from protobuf field <code>string lastName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string canonicalName = 3;</code>
     * @return string
     */
    public function getCanonicalName()
    {
        return $this->canonicalName;
    }

    /**
     * Generated from protobuf field <code>string canonicalName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->canonicalName = $var;

        return $this;
    }

}

