<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderedListPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OrderedListSearchRespPb</code>
 */
class OrderedListSearchRespPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.SummaryPb summary = 1;</code>
     */
    protected $summary = null;
    /**
     * Generated from protobuf field <code>repeated .OrderedListPb orderListresults = 2;</code>
     */
    private $orderListresults;
    /**
     * Generated from protobuf field <code>repeated .BuyPb buyListresults = 3;</code>
     */
    private $buyListresults;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\SummaryPb $summary
     *     @type \App\Protobuff\OrderedListPb[]|\Google\Protobuf\Internal\RepeatedField $orderListresults
     *     @type \App\Protobuff\BuyPb[]|\Google\Protobuf\Internal\RepeatedField $buyListresults
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\OrderedListPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.SummaryPb summary = 1;</code>
     * @return \App\Protobuff\SummaryPb
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>.SummaryPb summary = 1;</code>
     * @param \App\Protobuff\SummaryPb $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\SummaryPb::class);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OrderedListPb orderListresults = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderListresults()
    {
        return $this->orderListresults;
    }

    /**
     * Generated from protobuf field <code>repeated .OrderedListPb orderListresults = 2;</code>
     * @param \App\Protobuff\OrderedListPb[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderListresults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protobuff\OrderedListPb::class);
        $this->orderListresults = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .BuyPb buyListresults = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBuyListresults()
    {
        return $this->buyListresults;
    }

    /**
     * Generated from protobuf field <code>repeated .BuyPb buyListresults = 3;</code>
     * @param \App\Protobuff\BuyPb[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBuyListresults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protobuff\BuyPb::class);
        $this->buyListresults = $arr;

        return $this;
    }

}

