<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderedListPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OrderedListSearchReqPb</code>
 */
class OrderedListSearchReqPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderParentId = 1;</code>
     */
    protected $orderParentId = '';
    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     */
    protected $customerId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderParentId
     *     @type string $customerId
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\OrderedListPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderParentId = 1;</code>
     * @return string
     */
    public function getOrderParentId()
    {
        return $this->orderParentId;
    }

    /**
     * Generated from protobuf field <code>string orderParentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderParentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Generated from protobuf field <code>string customerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

}

