<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paymentPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>PaymentModeEnum</code>
 */
class PaymentModeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_MODE = 0;</code>
     */
    const UNKNOWN_MODE = 0;
    /**
     * Generated from protobuf enum <code>GOOGLE_PAY = 1;</code>
     */
    const GOOGLE_PAY = 1;
    /**
     * Generated from protobuf enum <code>CASH_ON_DELIVERY = 2;</code>
     */
    const CASH_ON_DELIVERY = 2;

    private static $valueToName = [
        self::UNKNOWN_MODE => 'UNKNOWN_MODE',
        self::GOOGLE_PAY => 'GOOGLE_PAY',
        self::CASH_ON_DELIVERY => 'CASH_ON_DELIVERY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

