<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paymentPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PaymentPbRef</code>
 */
class PaymentPbRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.PaymentStatusEnum status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>.PaymentModeEnum mode = 3;</code>
     */
    protected $mode = 0;
    /**
     * Generated from protobuf field <code>float amount = 4;</code>
     */
    protected $amount = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $status
     *     @type int $mode
     *     @type float $amount
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\PaymentPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PaymentStatusEnum status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.PaymentStatusEnum status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\PaymentStatusEnum::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PaymentModeEnum mode = 3;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.PaymentModeEnum mode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\PaymentModeEnum::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float amount = 4;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>float amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkFloat($var);
        $this->amount = $var;

        return $this;
    }

}

