<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customerPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>PrivilegeTypeEnum</code>
 */
class PrivilegeTypeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PREVILAGE = 0;</code>
     */
    const UNKNOWN_PREVILAGE = 0;
    /**
     * Generated from protobuf enum <code>NORMAL = 1;</code>
     */
    const NORMAL = 1;
    /**
     * Generated from protobuf enum <code>ADMIN = 2;</code>
     */
    const ADMIN = 2;
    /**
     * Generated from protobuf enum <code>DELIVERY_MAN = 3;</code>
     */
    const DELIVERY_MAN = 3;

    private static $valueToName = [
        self::UNKNOWN_PREVILAGE => 'UNKNOWN_PREVILAGE',
        self::NORMAL => 'NORMAL',
        self::ADMIN => 'ADMIN',
        self::DELIVERY_MAN => 'DELIVERY_MAN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

