<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pushNotificationPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PushNotificationPb</code>
 */
class PushNotificationPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     */
    protected $dbInfo = null;
    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 2;</code>
     */
    protected $customerRef = null;
    /**
     * Generated from protobuf field <code>string token = 3;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     */
    protected $time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuff\EntityPb $dbInfo
     *     @type \App\Protobuff\CustomerPbRef $customerRef
     *     @type string $token
     *     @type \App\Protobuff\TimePb $time
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\PushNotificationPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @return \App\Protobuff\EntityPb
     */
    public function getDbInfo()
    {
        return isset($this->dbInfo) ? $this->dbInfo : null;
    }

    public function hasDbInfo()
    {
        return isset($this->dbInfo);
    }

    public function clearDbInfo()
    {
        unset($this->dbInfo);
    }

    /**
     * Generated from protobuf field <code>.EntityPb dbInfo = 1;</code>
     * @param \App\Protobuff\EntityPb $var
     * @return $this
     */
    public function setDbInfo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\EntityPb::class);
        $this->dbInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 2;</code>
     * @return \App\Protobuff\CustomerPbRef
     */
    public function getCustomerRef()
    {
        return isset($this->customerRef) ? $this->customerRef : null;
    }

    public function hasCustomerRef()
    {
        return isset($this->customerRef);
    }

    public function clearCustomerRef()
    {
        unset($this->customerRef);
    }

    /**
     * Generated from protobuf field <code>.CustomerPbRef customerRef = 2;</code>
     * @param \App\Protobuff\CustomerPbRef $var
     * @return $this
     */
    public function setCustomerRef($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\CustomerPbRef::class);
        $this->customerRef = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 3;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     * @return \App\Protobuff\TimePb
     */
    public function getTime()
    {
        return isset($this->time) ? $this->time : null;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * Generated from protobuf field <code>.TimePb time = 4;</code>
     * @param \App\Protobuff\TimePb $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuff\TimePb::class);
        $this->time = $var;

        return $this;
    }

}

