<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requestPb.proto

/**
 * Protobuf type <code>RequestMethodEnum</code>
 */
class RequestMethodEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_METHOD = 0;</code>
     */
    const UNKNOWN_METHOD = 0;
    /**
     * Generated from protobuf enum <code>GET = 1;</code>
     */
    const GET = 1;
    /**
     * Generated from protobuf enum <code>POST = 2;</code>
     */
    const POST = 2;
    /**
     * Generated from protobuf enum <code>PUT = 3;</code>
     */
    const PUT = 3;

    private static $valueToName = [
        self::UNKNOWN_METHOD => 'UNKNOWN_METHOD',
        self::GET => 'GET',
        self::POST => 'POST',
        self::PUT => 'PUT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

