<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pushNotificationPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>SendNotificationTypeEnum</code>
 */
class SendNotificationTypeEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_TYPE = 0;</code>
     */
    const UNKNOWN_TYPE = 0;
    /**
     * Generated from protobuf enum <code>SINGLE = 1;</code>
     */
    const SINGLE = 1;
    /**
     * Generated from protobuf enum <code>MULTIPLE = 2;</code>
     */
    const MULTIPLE = 2;

    private static $valueToName = [
        self::UNKNOWN_TYPE => 'UNKNOWN_TYPE',
        self::SINGLE => 'SINGLE',
        self::MULTIPLE => 'MULTIPLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

