<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pushNotificationPb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SendPushNotificationPb</code>
 */
class SendPushNotificationPb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string registrationId = 1;</code>
     */
    protected $registrationId = '';
    /**
     * Generated from protobuf field <code>repeated string registrationIds = 2;</code>
     */
    private $registrationIds;
    /**
     * Generated from protobuf field <code>.SendNotificationTypeEnum sendType = 3;</code>
     */
    protected $sendType = 0;
    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string body = 5;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>string imageUrl = 6;</code>
     */
    protected $imageUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $registrationId
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $registrationIds
     *     @type int $sendType
     *     @type string $subject
     *     @type string $body
     *     @type string $imageUrl
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\PushNotificationPb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string registrationId = 1;</code>
     * @return string
     */
    public function getRegistrationId()
    {
        return $this->registrationId;
    }

    /**
     * Generated from protobuf field <code>string registrationId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->registrationId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string registrationIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegistrationIds()
    {
        return $this->registrationIds;
    }

    /**
     * Generated from protobuf field <code>repeated string registrationIds = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegistrationIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->registrationIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.SendNotificationTypeEnum sendType = 3;</code>
     * @return int
     */
    public function getSendType()
    {
        return $this->sendType;
    }

    /**
     * Generated from protobuf field <code>.SendNotificationTypeEnum sendType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSendType($var)
    {
        GPBUtil::checkEnum($var, \App\Protobuff\SendNotificationTypeEnum::class);
        $this->sendType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 6;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return $this->imageUrl;
    }

    /**
     * Generated from protobuf field <code>string imageUrl = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageUrl = $var;

        return $this;
    }

}

