<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressPb.proto

namespace App\Protobuff;

use UnexpectedValueException;

/**
 * Protobuf type <code>StateEnum</code>
 */
class StateEnum
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_STATE = 0;</code>
     */
    const UNKNOWN_STATE = 0;
    /**
     * Generated from protobuf enum <code>UTTAR_PRADESH = 1;</code>
     */
    const UTTAR_PRADESH = 1;

    private static $valueToName = [
        self::UNKNOWN_STATE => 'UNKNOWN_STATE',
        self::UTTAR_PRADESH => 'UTTAR_PRADESH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

