<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timePb.proto

namespace App\Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TimeQueryRangePb</code>
 */
class TimeQueryRangePb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 startMilliseconds = 1;</code>
     */
    protected $startMilliseconds = 0;
    /**
     * Generated from protobuf field <code>int64 endMilliseconds = 2;</code>
     */
    protected $endMilliseconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $startMilliseconds
     *     @type int|string $endMilliseconds
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\TimePb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 startMilliseconds = 1;</code>
     * @return int|string
     */
    public function getStartMilliseconds()
    {
        return $this->startMilliseconds;
    }

    /**
     * Generated from protobuf field <code>int64 startMilliseconds = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartMilliseconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->startMilliseconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 endMilliseconds = 2;</code>
     * @return int|string
     */
    public function getEndMilliseconds()
    {
        return $this->endMilliseconds;
    }

    /**
     * Generated from protobuf field <code>int64 endMilliseconds = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndMilliseconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->endMilliseconds = $var;

        return $this;
    }

}

