<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressPb.proto

namespace App\GPBMetadata;

class AddressPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa010a0f6164647265737350622e70726f746f226b0a09416464726573735062120e0a06686f6d654e6f180120012809120e0a0673747265657418022001280912100a086c616e644d61726b180320012809120c0a0463697479180420012809120d0a057374617465180520012809120f0a0770696e636f64651806200128054222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

