<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booleanPb.proto

namespace App\GPBMetadata;

class BooleanPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a0f626f6f6c65616e50622e70726f746f2a2f0a0b426f6f6c65616e456e756d120b0a0744454641554c54100012080a0454525545100112090a0546414c534510024222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

