<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confirmOrderDeliveryPb.proto

namespace App\GPBMetadata;

class ConfirmOrderDeliveryPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\GPBMetadata\TimePb::initOnce();
        \App\GPBMetadata\BuyPb::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83020a1c636f6e6669726d4f7264657244656c697665727950622e70726f746f1a0b62757950622e70726f746f22a9010a16436f6e6669726d4f7264657244656c6976657279506212120a0a637573746f6d6572496418012001280912150a0d706172656e744f72646572496418022001280912190a096f726465724c69737418032003280b32062e427579506212150a0474696d6518042001280b32072e54696d65506212240a0673746174757318052001280e32142e49734f726465726564506c61636564456e756d120c0a04646174611806200328094222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

