<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactDetailPb.proto

namespace App\GPBMetadata;

class ContactDetailPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ada010a15636f6e7461637444657461696c50622e70726f746f22300a07456d61696c506212110a096c6f63616c5061727418012001280912120a0a646f6d61696e50617274180220012809221c0a084d6f62696c65506212100a086d6f62696c654e6f18012001280922450a0f436f6e7461637444657461696c506212170a05656d61696c18012001280b32082e456d61696c506212190a066d6f62696c6518022001280b32092e4d6f62696c6550624222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

