<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entityPb.proto

namespace App\GPBMetadata;

class EntityPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\GPBMetadata\TimePb::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99020a0e656e7469747950622e70726f746f22500a08456e746974795062120a0a026964180120012809121d0a086c69666554696d6518032001280e320b2e537461747573456e756d12190a066c6f63616c6518042001280b32092e4c6f63616c65506222320a084c6f63616c65506212260a0f64656661756c7454696d655a6f6e6518012001280e320d2e54696d655a6f6e65456e756d2a550a0a537461747573456e756d12120a0e554e4b4e4f574e5f5354415455531000120a0a064143544956451001120b0a0744454c455445441002120d0a0953555350554e4445441003120b0a07424c4f434b454410044222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

