<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genderPb.proto

namespace App\GPBMetadata;

class GenderPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a740a0e67656e64657250622e70726f746f2a360a0a47656e646572456e756d12120a0e554e4b4e4f574e5f47454e444552100012080a044d414c451001120a0a0646454d414c4510024222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

