<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagePb.proto

namespace App\GPBMetadata;

class ImagePb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a0d696d61676550622e70726f746f22160a07496d6167655062120b0a0375726c1801200128094222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

