<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginPb.proto

namespace App\GPBMetadata;

class LoginPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\GPBMetadata\EntityPb::initOnce();
        \App\GPBMetadata\TimePb::initOnce();
        \App\GPBMetadata\SummaryPb::initOnce();
        \App\GPBMetadata\CustomerPb::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb020a0d6c6f67696e50622e70726f746f1a0c74696d6550622e70726f746f1a0f73756d6d61727950622e70726f746f1a10637573746f6d657250622e70726f746f22720a074c6f67696e506212190a066462496e666f18012001280b32092e456e74697479506212230a0b637573746f6d657252656618022001280b320e2e437573746f6d6572506252656612150a0474696d6518032001280b32072e54696d65506212100a086d6f62696c654e6f18042001280922280a144c6f67696e53656172636852657175657374506212100a086d6f62696c654e6f180120012809224f0a154c6f67696e536561726368526573706f6e73655062121b0a0773756d6d61727918012001280b320a2e53756d6d617279506212190a07726573756c747318022003280b32082e4c6f67696e50624222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

