<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namePb.proto

namespace App\GPBMetadata;

class NamePb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a0c6e616d6550622e70726f746f22440a064e616d65506212110a0966697273744e616d6518012001280912100a086c6173744e616d6518022001280912150a0d63616e6f6e6963616c4e616d651803200128094222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

