<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registrationPb.proto

namespace App\GPBMetadata;

class RegistrationPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\GPBMetadata\CustomerPb::initOnce();
        \App\GPBMetadata\LoginPb::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b010a14726567697374726174696f6e50622e70726f746f1a0d6c6f67696e50622e70726f746f22480a0e526567697374726174696f6e5062121d0a08637573746f6d657218012001280b320b2e437573746f6d6572506212170a056c6f67696e18022001280b32082e4c6f67696e50624222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

