<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requestPb.proto

namespace App\GPBMetadata;

class RequestPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82010a0f7265717565737450622e70726f746f2a430a11526571756573744d6574686f64456e756d12120a0e554e4b4e4f574e5f4d4554484f44100012070a03474554100112080a04504f5354100212070a0350555410034222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

