<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summaryPb.proto

namespace App\GPBMetadata;

class SummaryPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a0f73756d6d61727950622e70726f746f22200a0953756d6d617279506212130a0b726573756c74436f756e741801200128054222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

