<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userPb.proto

namespace App\GPBMetadata;

class UserPb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\GPBMetadata\EntityPb::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a0c7573657250622e70726f746f22440a0655736572506212190a066462496e666f18012001280b32092e456e746974795062121f0a08757365725479706518022001280e320d2e5573657254797065456e756d2a370a0c5573657254797065456e756d12100a0c554e4b4e4f574e5f555345521000120a0a064e4f524d414c100112090a0541444d494e10024222ca020d4170705c50726f746f62756666e2020f4170705c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

