<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

namespace GPBMetadata;

class Entity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f010a0c656e746974792e70726f746f22370a08456e746974795062120a0a026964180120012809121f0a086c69666574696d6518022001280e320d2e4c69666574696d65456e756d2a3e0a0c4c69666574696d65456e756d120b0a07554e4b4e4f574e1000120a0a064143544956451001120a0a0644454c455445100212090a05424c4f434b1003620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

